python_sources()

python_tests(
    name="tests0",
    dependencies=[
        "py/libs/pybind#cffi",
        "py/libs/pybind#numba",
        "py/libs/nufft:nufft_dist",
        "py/libs/pybind:pybind_dist",
    ],
)
