pex_binary(
    name="test_nufft1d",
    entry_point="test_nufft1d.py",
)

pex_binary(
    name="test_nufft1d_dft",
    entry_point="test_nufft1d_dft.py",
)

pex_binary(
    name="test_nufft2d",
    entry_point="test_nufft2d.py",
)

pex_binary(
    name="test_nufft3d",
    entry_point="test_nufft3d.py",
)

python_tests(
    dependencies=[
        "py/libs/nufft:nufft_dist",
    ]
)
